---

- hosts: all
  become: true
  tasks:

  - name: install java package
    yum:
      name: java
      state: latest

  - name: update repository index
    yum:
      update_cache: yes

  - name: install git
    yum:
      name: git 
