---
 
- hosts: all
  become: true
  pre_tasks:
 
  - name: update repository index (RedHat)
    tags: always
    yum:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "RedHat"
 
  - name: update repository index (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"
 
- hosts: all
  become: true
  roles:
    - base
    
- hosts: workstation
  become: true
  roles:
    - workstation
 
- hosts: web_server
  become: true
  roles:
    - web_server
 
- hosts: db_server
  become: true
  roles:
    - db_server
 
- hosts: file_server
  become: true
  roles:
    - file_server
